// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

struct AABB {
    float3 min, max;
};

RWStructuredBuffer<AABB> _Result;
float _Time;

[numthreads(8,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID) {
    uint index = id.x;
    if(index < _Result.Length){
        AABB bounds;
        float time = _Time + float((index & 15) + (index / 16));
        float3 pos = float3(float(index & 15) + cos(time), 3.0 + sin(time), float(index/16));
        float3 size = float3(1,1,1)*0.9;
        bounds.min = pos - size/2;
        bounds.max = pos + size/2;
        _Result[index] = bounds;
    }
}
