#pragma kernel SurfelsToAABBs

#include "Surfel.cginc"

uint3 _DispatchOffset;

RWStructuredBuffer<Surfel> _Surfels;
RWStructuredBuffer<AABB> _AABBs;

[numthreads(512,1,1)]
void SurfelsToAABBs(uint3 dispatchIdx : SV_DispatchThreadID) {
    uint index = dispatchIdx.x + _DispatchOffset.x;
    if(index < _Surfels.Length) {
        float4 pos = _Surfels[index].position;
        AABB b;
        b.min = pos.xyz - pos.w;
        b.max = pos.xyz + pos.w;
        _AABBs[index] = b;
    }
}
